import type { ShaderEntry, ShaderUniform } from "./shader-store";

function glslTypeToLuaType(type: string): string {
    switch (type) {
        case "float":
        case "int":
            return "number";
        case "vec2":
            return "{number, number}";
        case "vec3":
            return "{number, number, number}";
        case "vec4":
            return "{number, number, number, number}";
        case "bool":
            return "boolean";
        case "sampler2D":
            return "Image";
        default:
            return "any";
    }
}

function uniformDefaultLua(u: ShaderUniform): string {
    if (Array.isArray(u.value)) {
        return `{${(u.value as number[]).map((v) => v.toFixed(4)).join(", ")}}`;
    }
    if (typeof u.value === "boolean") return u.value ? "true" : "false";
    return (u.value as number).toFixed(4);
}

export function convertToLove2D(shader: ShaderEntry): string {
    const userLines = shader.fragmentSource.split("\n");

    const converted = userLines
        .map((line) => {
            return line.replace(/\btexture2D\s*\(/g, "Texel(").replace(/\btexture\s*\(/g, "Texel(");
        })
        .join("\n");

    const extraExterns = shader.uniforms
        .map((u) => `extern ${u.type} ${u.name};  -- ${glslTypeToLuaType(u.type)}`)
        .join("\n");

    const glslFile = `// SlimShader export — Love2D compatible GLSL
// Generated by SlimShader

// Built-in Love2D uniforms are handled automatically.
// Additional uniforms must be sent via shader:send() in main.lua.

${extraExterns ? extraExterns + "\n" : ""}
${converted}

// Love2D entry point — wraps mainImage
vec4 effect(vec4 color, Image tex, vec2 texture_coords, vec2 screen_coords) {
    vec4 fragColor;
    mainImage(fragColor, screen_coords);
    return fragColor;
}
`;

    return glslFile;
}

export function generateMainLua(shader: ShaderEntry): string {
    const sendCalls = [
        `    shader:send("iResolution", {love.graphics.getWidth(), love.graphics.getHeight()})`,
        `    shader:send("iTime", elapsed)`,
        `    shader:send("iMouse", {love.mouse.getPosition(), 0, 0})`,
        ...shader.uniforms
            .filter((u) => u.type !== "sampler2D")
            .map((u) => `    -- shader:send("${u.name}", ${uniformDefaultLua(u)})`),
    ].join("\n");

    return `-- SlimShader export — ${shader.name}
-- Generated by SlimShader

local shader
local elapsed = 0

function love.load()
    shader = love.graphics.newShader("shader.glsl")
end

function love.update(dt)
    elapsed = elapsed + dt
end

function love.draw()
${sendCalls}

    love.graphics.setShader(shader)
    love.graphics.rectangle("fill", 0, 0, love.graphics.getWidth(), love.graphics.getHeight())
    love.graphics.setShader()
end
`;
}

export function generateConfLua(shader: ShaderEntry): string {
    return `-- Love2D config — ${shader.name}
function love.conf(t)
    t.title = "${shader.name}"
    t.window.width = 800
    t.window.height = 600
    t.window.resizable = true
    t.window.vsync = 1
end
`;
}

export function generateReadme(shader: ShaderEntry): string {
    const uniformDocs =
        shader.uniforms.length > 0
            ? shader.uniforms
                  .map(
                      (u) =>
                          `  - \`${u.name}\` (${u.type}): default ${uniformDefaultLua(u)}\n    Uncomment and edit the send() call in main.lua`
                  )
                  .join("\n")
            : "  None defined.";

    return `# ${shader.name}
Exported by SlimShader.

## Running
1. Install [Love2D](https://love2d.org/)
2. \`love .\` inside this folder

## Custom uniforms
${uniformDocs}
`;
}
