/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ShaderShaderIdRouteImport } from './routes/shader.$shaderId'
import { Route as EditorShaderIdRouteImport } from './routes/editor.$shaderId'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShaderShaderIdRoute = ShaderShaderIdRouteImport.update({
  id: '/shader/$shaderId',
  path: '/shader/$shaderId',
  getParentRoute: () => rootRouteImport,
} as any)
const EditorShaderIdRoute = EditorShaderIdRouteImport.update({
  id: '/editor/$shaderId',
  path: '/editor/$shaderId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/gallery': typeof GalleryRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/editor/$shaderId': typeof EditorShaderIdRoute
  '/shader/$shaderId': typeof ShaderShaderIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/gallery': typeof GalleryRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/editor/$shaderId': typeof EditorShaderIdRoute
  '/shader/$shaderId': typeof ShaderShaderIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/gallery': typeof GalleryRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/editor/$shaderId': typeof EditorShaderIdRoute
  '/shader/$shaderId': typeof ShaderShaderIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/gallery'
    | '/login'
    | '/reset-password'
    | '/editor/$shaderId'
    | '/shader/$shaderId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/gallery'
    | '/login'
    | '/reset-password'
    | '/editor/$shaderId'
    | '/shader/$shaderId'
  id:
    | '__root__'
    | '/'
    | '/gallery'
    | '/login'
    | '/reset-password'
    | '/editor/$shaderId'
    | '/shader/$shaderId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GalleryRoute: typeof GalleryRoute
  LoginRoute: typeof LoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  EditorShaderIdRoute: typeof EditorShaderIdRoute
  ShaderShaderIdRoute: typeof ShaderShaderIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shader/$shaderId': {
      id: '/shader/$shaderId'
      path: '/shader/$shaderId'
      fullPath: '/shader/$shaderId'
      preLoaderRoute: typeof ShaderShaderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/editor/$shaderId': {
      id: '/editor/$shaderId'
      path: '/editor/$shaderId'
      fullPath: '/editor/$shaderId'
      preLoaderRoute: typeof EditorShaderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GalleryRoute: GalleryRoute,
  LoginRoute: LoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  EditorShaderIdRoute: EditorShaderIdRoute,
  ShaderShaderIdRoute: ShaderShaderIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
