/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EditorShaderIdRouteImport } from './routes/editor.$shaderId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EditorShaderIdRoute = EditorShaderIdRouteImport.update({
  id: '/editor/$shaderId',
  path: '/editor/$shaderId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/editor/$shaderId': typeof EditorShaderIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/editor/$shaderId': typeof EditorShaderIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/editor/$shaderId': typeof EditorShaderIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/editor/$shaderId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/editor/$shaderId'
  id: '__root__' | '/' | '/editor/$shaderId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EditorShaderIdRoute: typeof EditorShaderIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/editor/$shaderId': {
      id: '/editor/$shaderId'
      path: '/editor/$shaderId'
      fullPath: '/editor/$shaderId'
      preLoaderRoute: typeof EditorShaderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EditorShaderIdRoute: EditorShaderIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
